services:
  db:
    image: postgres:17-alpine
    container_name: audio_db
    environment:
      POSTGRES_USER: audio
      POSTGRES_PASSWORD: audio123
      POSTGRES_DB: audiodb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U audio -d audiodb"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
